server:
  port: 8080
spring:
  config:
    import:
      - 'optional:aws-parameterstore:/commit-attack/production/'
  datasource:
    url: jdbc:postgresql://${host}:5432/commitattack
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: VARCHAR
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com:
      commitAttack: DEBUG
    org:
      springframework: DEBUG
      hibernate:
        orm:
          jdbc:
            bind: trace


spring-doc:
  swagger-ui:
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  packagesToScan: com.commitAttack.be
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
    version: openapi_3_1
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

swagger-servers:
  urls:
    - http://commit-attack-application.ap-northeast-2.elasticbeanstalk.com
    - https://api.commitattack.app

github:
  client-id: ${github.clientId}
  client-secret: ${github.clientsecret}

jwt:
  common:
    key: ${jwt.key}
